"basic conf
set relativenumber
set number
set cursorline
set showcmd
set nocompatible
filetype plugin on
syntax on

"vimwiki_options
let wiki_welcome = {}
let wiki_welcome.path = '~/vimwiki/'
let wiki_welcome.path_html = '/var/www/html/'
let wiki_welcome.index = 'welcome'

let wiki_perk_tree = {}
let wiki_perk_tree.path = '~/vimwiki/perk_tree/'
let wiki_perk_tree.path_html = '/var/www/html/perk_tree'
let wiki_perk_tree.nested_syntaxes = {'python':'python', 'c++':'cpp'}

let wiki_cources = {}
let wiki_cources.path = '~/vimwiki/cources/'  
let wiki_cources.path_html = '/var/www/html/cources'
let wiki_cources.nested_syntaxes = {'python':'python', 'c++':'cpp'}

let g:vimwiki_list = [wiki_welcome, wiki_perk_tree, wiki_cources]
let g:vimwiki_valid_html_tags = 'b,i,s,u,br,hr,div,code'
"key_map
map <S-F4> :Vimwiki2HTML<cr>
map <F4> :VimwikiAll2HTML<cr>
